import { cva, VariantProps } from 'class-variance-authority';

export const buttonVariants = cva('flex items-center justify-center', {
  variants: {
    fullWidth: {
      true: 'w-full',
      false: '',
    },
    height: {
      44: 'h-[44px]',
      48: 'h-[48px]',
      60: 'h-[60px]',
      72: 'h-[72px]',
    },
    bgColor: {
      primary: 'bg-primary-500',
      naverGreen: 'bg-naver-green',
      kakaoYellow: 'bg-kakao-yellow',
      googleGray: 'bg-google-gray',
      white: 'bg-white',
      gray900: 'bg-gray-900',
      gray100: 'bg-gray-100',
      gray200: 'bg-gray-200',
      gray300: 'bg-gray-300',
      gray400: 'bg-gray-400',
    },
    textColor: {
      primary: 'text-primary-500',
      naverGreen: 'text-naver-green',
      kakaoYellow: 'text-kakao-yellow',
      googleGray: 'text-google-gray',
      white: 'text-white',
      gray900: 'text-gray-900',
      gray100: 'text-gray-100',
      gray200: 'text-gray-200',
      gray300: 'text-gray-300',
      gray400: 'text-gray-400',
    },
    fontSize: {
      10: 'text-[10px]',
      12: 'text-[12px]',
      14: 'text-[14px]',
      16: 'text-[16px]',
      18: 'text-[18px]',
      20: 'text-[20px]',
      24: 'text-[24px]',
      32: 'text-[32px]',
      40: 'text-[40px]',
      48: 'text-[48px]',
    },
    fontWeight: {
      light: 'font-light',
      normal: 'font-normal',
      medium: 'font-medium',
      semibold: 'font-semibold',
      bold: 'font-bold',
    },
    rounded: {
      4: 'rounded-[4px]',
      8: 'rounded-[8px]',
      16: 'rounded-[16px]',
      24: 'rounded-[24px]',
      none: '',
    },
    borderPosition: {
      top: 'border-t',
      bottom: 'border-b',
      left: 'border-l',
      right: 'border-r',
    },
    borderWidth: {
      1: 'border-[1px]',
      2: 'border-[2px]',
      3: 'border-[3px]',
      4: 'border-[4px]',
    },
    borderStyle: {
      solid: 'border-solid',
      dashed: 'border-dashed',
      dotted: 'border-dotted',
      double: 'border-double',
      groove: 'border-groove',
      ridge: 'border-ridge',
      inset: 'border-inset',
      outset: 'border-outset',
    },
    borderColor: {
      primary: 'border-primary-500',
      naverGreen: 'border-naver-green',
      kakaoYellow: 'border-kakao-yellow',
      googleGray: 'border-google-gray',
      white: 'border-white',
      gray900: 'border-gray-900',
      gray100: 'border-gray-100',
      gray200: 'border-gray-200',
      gray300: 'border-gray-300',
      gray400: 'border-gray-400',
      none: 'border-none',
    },
    active: {
      true: 'active:opacity-90',
      false: '',
    },
    disabled: {
      true: 'cursor-not-allowed opacity-50',
      false: '',
    },
  },
  defaultVariants: {
    fullWidth: false,
    height: 48,
    bgColor: 'primary',
    textColor: 'white',
    fontSize: 16,
    fontWeight: 'bold',
    rounded: 'none',
    borderPosition: 'top',
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: 'none',
    active: false,
    disabled: false,
  },
});

export type ButtonVariantsProps = VariantProps<typeof buttonVariants>;
